<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>container</string>
		<string>ctn</string>
		<string>ctn.env</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>CCContainer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.ctn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.ctn</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.ctn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ctn</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.ctn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ctn</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#!).*$\n?</string>
			<key>name</key>
			<string>comment.line.shebang.ctn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ctn</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|use|namespace|when|override)\b</string>
			<key>name</key>
			<string>keyword.control.ctn</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(["'])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ctn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(["'])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ctn</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?xi)
  (?:\B[-+])?
  (?:
    (
      \B\.[0-9]+|               # e.g. .999
      \b[0-9]+(\.[0-9]*)?       # e.g. 999.999, 999. or 999
    )(e[-+]?[0-9]+)?            # e.g. e+123, E-123
  )</string>
			<key>name</key>
			<string>constant.numeric.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:[a-zA-Z0-9_\.]+</string>
			<key>name</key>
			<string>variable.parameter.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@container+</string>
			<key>name</key>
			<string>support.variable.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[a-zA-Z0-9_\.]+:</string>
			<key>name</key>
			<string>variable.other.object.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[a-zA-Z0-9_\.]+</string>
			<key>name</key>
			<string>support.variable.function.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\- ([a-zA-Z0-9_\.]+)</string>
			<key>name</key>
			<string>entity.name.function.ctn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)
  :(?!:)</string>
			<key>name</key>
			<string>keyword.operator.assignment.ctn</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cccontainer</string>
	<key>uuid</key>
	<string>b5698b0b-0c5b-4a56-9645-c8c90082f81d</string>
</dict>
</plist>
